name: security_monkey
description: An AWS Policy Monitoring and Alerting Tool
version: 1.1.1
dependencies:
  angular: "^1.1.2+2"
  angular_ui: ">=0.6.8 <0.7.0"
  hammock: ">=0.4.0 <0.5.0"
  ng_infinite_scroll: ">=0.2.0 <0.3.0"
  web_components: ">=0.10.1 <0.11.0"
  browser: ">=0.10.0+2 <0.11.0"
  http_server: ">=0.9.5+1 <0.10.0"
  code_transformers: ">=0.2.5 <0.3.0"
  dart_to_js_script_rewriter: ">=0.0.2 <0.1.0"
  aws_policy_expander_minimizer: ">=0.0.5 <0.1.0"
dev_dependencies:
  unittest: '0.11.0+2'
transformers:
 - angular
 - dart_to_js_script_rewriter
 - $dart2js:
    csp: true
    checked: false
    minify: true
    verbose: true
    suppressWarnings: false
    suppressHints: false
    terse: false
author: yes
homepage: https://github.com/Netflix/security_monkey
